using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.UI;

public class RoleHeroInfoComp : MonoBehaviour
{
    public Button closeBtn;
    public Image intelligenceBg;
    public Text intelligenceText;
    public Text newintelligenceText;
    public List<GUIIcon> allStars;
    public GameObject restObj;
    public GameObject exploreObj;
    public GameObject idleObj;
    public Button restBtn;
    public Text restingTimeText;
    public Button exploreBtn;
    public Text exploreTimeText;
    public Text professionNameTx;
    public GUIIcon typeIcon;
    public Transform roleTrans;
    public Button leftBtn;
    public Button rightBtn;
    public List<RoleSkillItemUI> allSkills;
    public GUIIcon talentIcon;
    public GUIIcon talentQualityIcon;
    public Text talentNameText;
    public Text talentDescText;
    public Text talentDescText2;
    public Text talentDescText3;
    public Text talentDescText4;
    public Text levelText;
    public Text scheduleText;
    public Text nickNameTx;
    public Slider levelSlider;
    public Button useLevelItemBtn;
    public Text fightingText;

    public Text canWearEquipClassText;
    public List<RoleEquipItemUI> allEquips;
    public Button settingBtn;
    public Button transferBtn;
    public GameObject topObj;
    public Button allWearBtn;
    public Text hintInfoText;
    public Text tempText;
    public GameObject secondaryInterfaceObj;
    public Button settingBgBtn;
    public Button renameBtn;
    public Button dismissalBtn;
    public GameObject renameObj;
    public InputField renameInput;
    public Button renameConfirmBtn;
    public Button renameCancleBtn;
    public Button renameCloseBtn;
    public GameObject dismissalObj;
    public Text dismissalNameText;
    public Button dismissalConfirmBtn;
    public Button dismissalCancleBtn;
    public Button dismissalCloseBtn;
    public Text dismissalNumText;
    public GameObject dismissalAgainObj;
    public Canvas bgCanvas;
    public Text transferText;
    public GameObject toTransferObj;
    public GUIIcon qualityIcon;
    public Button professionBtn;
    public List<GameObject> QualityFxList;
    public Button attBtn;
    public Text lifeTx;
    public Text atkTx;
    public Text armorTx;
    public Image transferRedPoint;
    public GUIIcon fightingChangeIcon;
    public GUIIcon hpChangeIcon;
    public GUIIcon atkChangeIcon;
    public GUIIcon defChangeIcon;
    public Text fightingChangeText;
    public Text hpChangeText;
    public Text atkChangeText;
    public Text defChangeText;
    public Button hpAddBtn;
    public Button atkAddBtn;
    public Button defAddBtn;

    public GUIIcon intelligenceBgIcon;
    public Transform headParent;
    public Image limitImg;

    public Text fireLvText;
    public GUIIcon fireBgIcon;
    public GUIIcon fireIntelligenceIcon;
    public Transform fireRoleDressTrans;
    public GUIIcon fireTypeBgIcon;
    public GUIIcon fireTypeIcon;
    public Text fireIntelligenceText;
    public List<GUIIcon> fireAllStars;
    public GameObject firePromptText;
    public GameObject fireReturnObj;
    public GameObject fireLineSecondObj;
    public List<GUIIcon> fireAllReturnIcons;
    public List<Text> fireAllReturnText;

    public Button btn_transferNumLimitDes;
    public Button btn_transferNumLimitDesView;
    public RectTransform rtf_transferNumLimitDesViewBg;
    public RectTransform rtf_transferNumLimitDesViewContent;

    public ToggleGroupMarget group;
    public GUIIcon typeBgIcon;
    public GameObject infoObj;
    public GameObject skillObj;
    public Text talentQualityStr;
    public Text talentXDescText;
    public ToggleGroupMarget skillGroup;
    public RectTransform skillArrowRect;
    public Text skillNameText;
    public Text skillDescText;

    public bool showCAttPanel;
    public Text equipNumText;
}
